### ISSUE TITLE
feature: adding some lints to increase code quality

### ISSUE THREAD

**Issue by logicalangel** [KenshiTech/unchained#76]
Generally, linters can help developers ensure code quality. As I know, in the Golang environment it's common to use this tool:
https://golangci-lint.run/

which aggregates lots of linters together and makes the ability to change using a config file. In the following, I will send a tuned config file based on my experience. Maybe it's necessary to fix some codes to meet linters, and after that, we can add the linter to the project's CI.

[golangci.txt](https://github.com/KenshiTech/unchained/files/14728326/golangci.txt)

and this tools also check handling of each error that can be used in CI:

https://github.com/kisielk/errcheck

**Comment by pouya-eghbali** [comment]
Let's set this up ASAP.
