### ISSUE TITLE
fix: Resolving all linters errors 

### ISSUE THREAD

**Issue by logicalangel** [KenshiTech/unchained#80]
After adding linters to the project, these show us lots of mishandled errors and a few problems on the code. we should fix them before adding linters to CI.
So, at the end of this task, the linters should work successfully in our CI

**Comment by pouya-eghbali** [comment]
@logicalangel should this be done before or after #75 ?

**Comment by logicalangel** [comment]
> @logicalangel should this be done before or after #75 ?

Should be done before it

**Comment by pouya-eghbali** [comment]
Cool, let's move forward with this, then.

**Comment by logicalangel** [comment]
Done and merged
