### ISSUE TITLE
Fix: Get rid of the go.work and use multi cmd pattern 

### ISSUE THREAD

**Issue by logicalangel** [KenshiTech/unchained#97]
As we know, our application can run in different modes, but they are related to each other and are not separated repositories. so using go.work is useless here.
we can handle this issue by creating different cmds and prevent things from being complicated.

In the end, we should have a go.mod in our project and a cmd directory that represents the applications we have

**Comment by pouya-eghbali** [comment]
@logicalangel `go.work` is to manage Unchained and the ZK Unchained projects from one repository. They're independent works. We could move zk to Unchained. That'd work. Let's remove the zk directory from the root, for now, we'll restore it when we need it.

**Comment by harpy-wings** [comment]
@pouya-eghbali can we remove the ZK from the unchained now and move it to another repository?
