### ISSUE TITLE
Feature: Add a commit convention

### ISSUE THREAD

**Issue by Dirdmaster** [KenshiTech/unchained#99]
# Context
As discussed with @pouya-eghbali, we need a better structure to our commit 

# Proposed change
I will make some guidelines and inforce them with some tooling. Such as:
- [Commitizen](https://commitizen-tools.github.io/commitizen/)
- [Husky](https://github.com/typicode/husky)

**Comment by pouya-eghbali** [comment]
@Dirdmaster we need to make sure we document this for everyone to follow.
